export const initialData = {
  users: [
    {
      id: 'customer-1',
      name: 'Priya Sharma',
      phone: '+919876543210',
      role: 'customer',
      city: 'Rewa',
    },
    {
      id: 'admin-1',
      name: 'Operations Director',
      phone: '+910000000000',
      role: 'admin',
      city: 'New Delhi',
    },
  ],
  services: [
    {
      id: 'party-makeup',
      name: 'Signature Party Look',
      icon: '💄',
      price: 1899,
      duration: '75 min',
      description: 'Sophisticated HD glam featuring flawless base matching, eye definition, and editorial-grade lip artistry.',
    },
    {
      id: 'bridal-makeup',
      name: 'Elite Bridal Couture',
      icon: '👰',
      price: 12999,
      duration: '4.5 hr',
      description: 'Masterclass bridal styling including premium HD/Airbrush makeup, intricate hairstyling, and couture draping.',
    },
    {
      id: 'engagement-makeup',
      name: 'Radiant Engagement',
      icon: '💍',
      price: 5499,
      duration: '2.5 hr',
      description: 'Camera-ready elegance designed for high-end photography, featuring precision contouring and graceful styling.',
    },
    {
      id: 'hair-styling',
      name: 'Artisanal Hair Design',
      icon: '✨',
      price: 1199,
      duration: '60 min',
      description: 'Bespoke hairstyling from red-carpet waves to traditional buns, tailored to your face shape and outfit.',
    },
    {
      id: 'saree-draping',
      name: 'Precision Saree Draping',
      icon: '🪷',
      price: 699,
      duration: '30 min',
      description: 'Flawless pleating and architectural draping techniques for sarees, lehengas, and couture ensembles.',
    },
    {
      id: 'basic-beauty',
      name: 'Essential Glow Ritual',
      icon: '🌸',
      price: 999,
      duration: '90 min',
      description: 'Luxury grooming packages including deep-cleansing organic facials, precision threading, and relaxing care.',
    },
  ],
  artists: [
    {
      id: 'artist-1',
      name: 'Meena Kapoor | Elite Bridal Artistry',
      phone: '+919111111111',
      gender: 'Female',
      photo: '/src/assets/artist_meena.png',
      city: 'Rewa',
      serviceAreas: ['Shiv Colony', 'Saman', 'Civil Lines', 'Anantpur'],
      experience: '12 years',
      rating: 4.9,
      distance: 2.1,
      online: true,
      basePrice: 1200,
      skills: ['Luxury Bridal', 'Editorial', 'High-Fashion Hair'],
      portfolio: [],
      bankUpi: 'meenakapoor@upi',
    },
    {
      id: 'artist-2',
      name: 'Sana Khan | Modern Glam Specialist',
      phone: '+919222222222',
      gender: 'Female',
      photo: '/src/assets/artist_sana.png',
      city: 'Satna',
      serviceAreas: ['Bus Stand', 'Bharhut Nagar', 'Semariya Road'],
      experience: '7 years',
      rating: 4.8,
      distance: 3.4,
      online: true,
      basePrice: 800,
      skills: ['Party Glam', 'Saree Couture', 'Contemporary Style'],
      portfolio: [],
      bankUpi: 'sanakhan@upi',
    },
    {
      id: 'artist-3',
      name: 'Ritu Varma | HD Makeup Studio',
      phone: '+919333333333',
      gender: 'Female',
      photo: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=400&q=80',
      city: 'Katni',
      serviceAreas: ['Madhav Nagar', 'Jabalpur Road'],
      experience: '15 years',
      rating: 5.0,
      distance: 5.6,
      online: false,
      basePrice: 1500,
      skills: ['Pro HD Makeup', 'Cinematic Styling', 'Expert Draping'],
      portfolio: [],
      bankUpi: 'rituvarma@upi',
    },
  ],
  bookings: [
    {
      id: 'booking-1',
      serviceId: 'party-makeup',
      serviceName: 'Signature Party Look',
      customerId: 'customer-1',
      customerName: 'Priya Sharma',
      artistId: 'artist-1',
      requestedArtistId: 'artist-1',
      artistName: 'Meena Kapoor',
      city: 'Rewa',
      date: '2026-04-26',
      time: '17:00',
      address: 'House No. 42, Shiv Colony, Rewa',
      location: { lat: 24.5362, lng: 81.3037 },
      price: 1899,
      duration: '75 min',
      paymentMode: 'cash',
      paymentStatus: 'cash_pending',
      status: 'accepted',
      createdAt: Date.now() - 3600000,
    },
  ],
  reviews: [
    {
      id: 'review-1',
      artistId: 'artist-1',
      artistName: 'Meena Kapoor',
      customerId: 'customer-1',
      rating: 5,
      comment: 'Absolutely stunning work. Meena was punctual and handled the look with incredible precision.',
    },
  ],
  payments: [],
  coupons: [
    {
      id: 'PREMIUM10',
      title: 'Luxury Welcome Offer',
      discountPercent: 10,
      city: 'Rewa',
    },
  ],
  notifications: [],
  admin_settings: {
    defaultCommissionPercent: 18,
    supportPhone: '+91 90000 00000',
  },
};

